name: Deploy on release published
on:

  release:
    types: [published]

jobs:
  Deploy_published_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: echo deploy
        run: echo "deploy"
      
      - name: echo release
        run: echo ${{ github.ref }}
      
      - name: echo commit
        run: echo ${{ github.sha }}
